version: "3.7"
services:
  funcaptcha-token-webservice:
    container_name: funcaptcha-token-webservice
    image: ${DOCKER_IMAGE:-rafaelcalleja/funcaptcha-token:latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT:-9000}:9000
    restart: unless-stopped
